[build]
  command = "npm install"
  publish = "."
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin/*"
  to = "/admin-dashboard.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions.environment]
  ADMIN_TOKEN = "your-secure-admin-token"
  NETLIFY_SITE_ID = "your-site-id"
  NETLIFY_API_TOKEN = "your-api-token"
  SENDGRID_API_KEY = "your-sendgrid-api-key"
  ADMIN_EMAIL = "your-admin-email@example.com" 