[build]
  command = "npm install"
  publish = "templates"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/admin/*"
  to = "/admin-dashboard.html"
  status = 200

[functions]
  node_bundler = "esbuild"

[functions.environment]
  ADMIN_TOKEN = "your-secure-admin-token"
  NETLIFY_SITE_ID = "your-site-id"
  NETLIFY_API_TOKEN = "your-api-token"
  SENDGRID_API_KEY = "your-sendgrid-api-key"
  ADMIN_EMAIL = "your-admin-email@example.com"
  FIREBASE_TYPE = "service_account"
  FIREBASE_PROJECT_ID = "your-project-id"
  FIREBASE_PRIVATE_KEY_ID = "your-private-key-id"
  FIREBASE_PRIVATE_KEY = "your-private-key"
  FIREBASE_CLIENT_EMAIL = "your-client-email"
  FIREBASE_CLIENT_ID = "your-client-id"
  FIREBASE_AUTH_URI = "https://accounts.google.com/o/oauth2/auth"
  FIREBASE_TOKEN_URI = "https://oauth2.googleapis.com/token"
  FIREBASE_AUTH_PROVIDER_CERT_URL = "https://www.googleapis.com/oauth2/v1/certs"
  FIREBASE_CLIENT_CERT_URL = "your-client-cert-url"